import { Monster } from '@/models/monster';

export const monsters: Monster[] = [
  {
    id: 'hydra-prime',
    name: 'Hydra Prime',
    level: 18,
    element: 'Water',
    health: 260,
    attack: 34,
    defense: 22,
    recommendedStr: 16,
    description:
      'A regenerative serpent that splits into new heads when struck. Target the core crystal to stop the regen.',
    xpReward: 120,
    featuredLoot: 'Phoenix Feather',
  },
  {
    id: 'storm-wyrm',
    name: 'Storm Wyrm',
    level: 14,
    element: 'Lightning',
    health: 210,
    attack: 30,
    defense: 16,
    recommendedStr: 14,
    description: 'Sweeps the arena with charged winds that punish low agility.',
    xpReward: 100,
    featuredLoot: 'Tempest Scale',
  },
  {
    id: 'iron-golem',
    name: 'Iron Golem',
    level: 12,
    element: 'Earth',
    health: 240,
    attack: 24,
    defense: 28,
    recommendedStr: 15,
    description: 'Slow but unyielding guardian forged from haunted steel.',
    xpReward: 90,
    featuredLoot: 'Shard of Fortitude',
  },
  {
    id: 'night-geist',
    name: 'Night Geist',
    level: 16,
    element: 'Shadow',
    health: 200,
    attack: 32,
    defense: 18,
    recommendedStr: 13,
    description: 'Phases in and out of reality to siphon stamina.',
    xpReward: 110,
    featuredLoot: 'Void Cloak',
  },
  {
    id: 'ember-rat',
    name: 'Ember Rat',
    level: 5,
    element: 'Fire',
    health: 120,
    attack: 16,
    defense: 8,
    recommendedStr: 8,
    description: 'A fiery scavenger that ignites the ground with each scurry.',
    xpReward: 60,
    featuredLoot: 'Cinder Tail',
  },
  {
    id: 'sapling-guardian',
    name: 'Sapling Guardian',
    level: 2,
    element: 'Earth',
    health: 90,
    attack: 10,
    defense: 6,
    recommendedStr: 4,
    description: 'A tiny treant that defends the forest with thorny vines.',
    xpReward: 35,
    featuredLoot: 'Verdant Twig',
  },
  {
    id: 'tidal-sprite',
    name: 'Tidal Sprite',
    level: 3,
    element: 'Water',
    health: 100,
    attack: 12,
    defense: 7,
    recommendedStr: 5,
    description: 'Splashes attackers with bursts of pressurized surf.',
    xpReward: 40,
    featuredLoot: 'Bubble Pearl',
  },
  {
    id: 'gale-fox',
    name: 'Gale Fox',
    level: 4,
    element: 'Air',
    health: 110,
    attack: 14,
    defense: 8,
    recommendedStr: 6,
    description: 'Dashes around opponents, slicing with wind-forged tails.',
    xpReward: 50,
    featuredLoot: 'Wind Tail',
  },
  {
    id: 'dune-scorpion',
    name: 'Dune Scorpion',
    level: 7,
    element: 'Earth',
    health: 150,
    attack: 18,
    defense: 12,
    recommendedStr: 9,
    description: 'Ambushes foes beneath the sand with venom-tipped claws.',
    xpReward: 70,
    featuredLoot: 'Sting Barbs',
  },
  {
    id: 'glacier-owl',
    name: 'Glacier Owl',
    level: 9,
    element: 'Air',
    health: 170,
    attack: 20,
    defense: 14,
    recommendedStr: 10,
    description: 'Freezes prey mid-flight with glacial winds.',
    xpReward: 80,
    featuredLoot: 'Frost Feather',
  },
  {
    id: 'pyro-colossus',
    name: 'Pyro Colossus',
    level: 22,
    element: 'Fire',
    health: 320,
    attack: 40,
    defense: 26,
    recommendedStr: 20,
    description: 'An ancient molten sentinel that erupts with magma fists.',
    xpReward: 150,
    featuredLoot: 'Inferno Core',
  },
  {
    id: 'void-singer',
    name: 'Void Singer',
    level: 27,
    element: 'Shadow',
    health: 360,
    attack: 44,
    defense: 30,
    recommendedStr: 23,
    description: 'Channels cosmic echoes to shatter defenses.',
    xpReward: 180,
    featuredLoot: 'Echo Shard',
  },
  {
    id: 'terra-leviathan',
    name: 'Terra Leviathan',
    level: 32,
    element: 'Earth',
    health: 420,
    attack: 48,
    defense: 38,
    recommendedStr: 28,
    description: 'A slumbering behemoth that crushes foes with tectonic waves.',
    xpReward: 210,
    featuredLoot: 'Gaia Scale',
  },
  {
    id: 'astral-phoenix',
    name: 'Astral Phoenix',
    level: 40,
    element: 'Air',
    health: 480,
    attack: 56,
    defense: 34,
    recommendedStr: 32,
    description: 'Reborn from stardust, bathes the arena in celestial fire.',
    xpReward: 260,
    featuredLoot: 'Stellar Plume',
  },
];
